name: Checks

on:
  push:
    branches:
      - 'main'
  pull_request:


jobs:
  run_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash

    - name: Verify dependencies complete
      run: python3 prep_turbomole_calc.py --dont-execute
      shell: bash

    - name: Type checking
      uses: jakebailey/pyright-action@v1
